if empty(glob('~/.config/vim/autoload/plug.vim'))
       silent !curl -fLo ~/.config/vim/autoload/plug.vim --create-dirs
         \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
       autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
    endif
"set nocompatible
syntax enable
let mapleader = ' '

set number relativenumber
set noswapfile
set scrolloff=5
set backspace=indent,eol,start

" Pythonic stuff
set tabstop=4
set expandtab
set softtabstop=4
set shiftwidth=4
set autoindent
set fileformat=unix

set hidden

set wildmenu
set hlsearch

set ignorecase
set smartcase

set laststatus=2

"set mouse=a
set cmdheight=2
map Y y$
set ttimeoutlen=50

call plug#begin('~/.config/vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'jiangmiao/auto-pairs' 

Plug 'morhetz/gruvbox' 
call plug#end()

let g:airline_theme='gruvbox'

colorscheme gruvbox
let g:gruvbox_transparent_bg = 1
set background=dark
highlight Normal     ctermbg=NONE guibg=NONE
highlight LineNr     ctermbg=NONE guibg=NONE
highlight SignColumn ctermbg=NONE guibg=NONE

nnoremap ; :
nnoremap : ;
nmap <leader>h :bn<CR>
nmap <leader>l :bp<CR>
nmap <C-w> :bd<CR>
