if empty(glob('~/.config/vim/autoload/plug.vim'))
       silent !curl -fLo ~/.config/vim/autoload/plug.vim --create-dirs
         \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
       autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
    endif
"set nocompatible
syntax on

set number
set relativenumber

set tabstop=4
set expandtab
set hidden

set wildmenu
set hlsearch

set ignorecase
set smartcase

set backspace=indent,eol,start
set autoindent
set laststatus=2

"set mouse=a
set cmdheight=2
map Y y$
set ttimeoutlen=50

call plug#begin('~/.config/vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'morhetz/gruvbox' 
call plug#end()




