#!/bin/bash
set NODE_OPTIONS=--max-old-space-size=4096
jupyter labextension install @aquirdturtle/collapsible_headings  --no-build 
jupyter labextension install @axlair/jupyterlab_vim  --no-build 
jupyter labextension install jupyterlab-vimrc  --no-build 
jupyter labextension install jupyterlab_vim-system-clipboard-support  --no-build 
jupyter lab build
jupyter nbextension enable --py widgetsnbextension
set NODE_OPTIONS=
