#!/bin/bash
set NODE_OPTIONS=--max-old-space-size=4096
jupyter labextension install @aquirdturtle/collapsible_headings v2.2.0 --no-build 
jupyter labextension install @axlair/jupyterlab_vim v0.12.4 --no-build 
jupyter labextension install jupyterlab-vimrc v0.3.0 --no-build 
jupyter labextension install jupyterlab_vim-system-clipboard-support v0.2.0 --no-build 
jupyter lab build
set NODE_OPTIONS=
